### ISSUE TITLE
security isue

### ISSUE THREAD

**Issue by domenkozar** [nix-community/docker-nix#17]
https://justi.cz/security/2018/09/13/alpine-apk-rce.html

@zimbatim is this repo affected?

**Comment by zimbatm** [comment]
TL;DR: We're all good.

New alpine images have been pushed by upstream with the same tag which fixes the hole for future builds.

For this particular project the security hole affects the installation at build time. Once bootstrapped the resulting images don't contain any alpine binaries.

Because the existing images are built by docker hub I think that it's fair to say that it's very unlikely for old images to have been MITMed and compromised as well.
